version: '2.4'

services:
  service-discovery:
    image: application/discovery-service:naive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
    ports:
      - 8761:8080

  examinator:
    image: application/examinator:naive
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8081:8081

  history:
    image: application/history:naive
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8082:8082

  mathematic:
    image: application/mathematic:naive
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      SERVER_PORT: 8083
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8083:8083
